name: Android CI
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Grant execute permission for gradlew
        working-directory: ./code
        run: chmod +x gradlew
      
      # Execute unit tests
      - name: Build with Gradle
        working-directory: ./code
        run: ./gradlew build
